# Generated by Django 4.1.4 on 2022-12-25 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bakar', '0003_alter_bakar_options_alter_bakar_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakar',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bakar',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bakar',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='bakar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bakar',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bakar',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
