# Generated by Django 4.1.4 on 2022-12-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakar', '0004_bakar_about_bakar_avatar_bakar_email_bakar_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakar',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='student'),
        ),
    ]
