# Generated by Django 4.1.4 on 2022-12-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakar', '0005_alter_bakar_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakar',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='student_files'),
        ),
    ]
