# Generated by Django 4.1.4 on 2022-12-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakar', '0006_bakar_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakar',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
