# Generated by Django 4.1.4 on 2022-12-26 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakar', '0007_alter_bakar_register_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bakar',
            table=None,
        ),
    ]
